// This script deploys the PriceMonitor contract for each token defined in tokens.json
const fs = require("fs");
const path = require("path");
const { ethers } = require("hardhat");
const TOKENS = require("../src/tokens.json");

async function main() {
  const PriceMonitor = await ethers.getContractFactory("PriceMonitor");
  const deployedContracts = {};

  for (const token of TOKENS) {
    const monitor = await PriceMonitor.deploy(token.feedAddress);
    await monitor.waitForDeployment();
    const addr = monitor.target ?? monitor.address;
    deployedContracts[token.id] = addr;
    console.log(`Deployed ${token.label} at: ${addr}`);
  }

  // Emit a JS module for frontend
  const out = path.join(__dirname, "../src/deployed-contracts.js");
  const content =
    "// Auto-generated by deploy.js\n" +
    "export const deployedContracts = " +
    JSON.stringify(deployedContracts, null, 2) +
    ";\n";
  fs.writeFileSync(out, content);
  console.log("✅ Written", out);
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
